### ISSUE TITLE
Toolbar: Color Scheme

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/spotlight#129]
The colors used by the toolbar are rather hard on the eye, maybe we can find some color combination (purple still), that has high contrast, but doesn't take us on the DOS or BIOS memory lane 😅

Website and Toolbar should be coherent in style/brand

**Comment by Lms24** [comment]
I'm going to close this for the moment because we adjusted the overlay and website UI since opening this issue. There's def room for improvement but I think it's unlikely that we're going to change the color scheme before the initial launch.

Let me know if there's something concretely that still needs fixing :)
