### ISSUE TITLE
Add @sentry/astro as peerDep of @spotlightjs/astro

### ISSUE THREAD

**Issue by HazAT** [getsentry/spotlight#203]

**Comment by Lms24** [comment]
After some experimentation we decided to go with adding the peer dependency. Not because it provides a lot of advantages when installing spotlight but because we can enforce a minimum SDK version which makes sense.

For future context: Specifying `@sentry/astro` as a peer dependency of `@spotlightjs/astro` will in fact install the package but not modify `astro.config.mjs`. So users will still either have to do this manually or run `npx spotlight add @sentry/astro` afterwards. To drive this point home, calling the `npx` command after installing spotlight will insert the sentry integration _after_ spotlight which requires yet another round of user intervention to correct the order. 

### Only running `npx spotlight add @spotlightjs/astro` 
![image](https://github.com/getsentry/spotlight/assets/8420481/0b148ee3-040f-4d43-926a-dee8b7c0a183)

### Running `npx astro add @sentry/astro @spotlightjs/astro `
![image](https://github.com/getsentry/spotlight/assets/8420481/c9bacf17-962d-445e-a764-af9df9ba73c4)

**Comment by Lms24** [comment]
closed via 9b7625ed1cb6f75ff67aa0423045641602985e1b
