### ISSUE TITLE
Clicks between spans will mess up router with escape key

### ISSUE THREAD

**Issue by lforst** [getsentry/spotlight#277]
I clicked between spans and then pressed ESC and it moved me between the spans again. Ideally, we close the drawer if esc is pressed.

https://github.com/getsentry/spotlight/assets/8118419/7619d67e-12c2-447d-bbb9-0c19011a1041

**Comment by Shubhdeep12** [comment]
Yes, this is an issue because of 2 reasons:

1. On clicking escape, we just go back in history of router.
2. We treat span detail as a new route, but on UI, it looks like a sidebar opened on top of the span tree page on clicking span.


Solution idea: according to me, solving 2nd reason makes sense by just making span detail a component instead of route(if in future we are not planning to change the UI).

**Comment by Shubhdeep12** [comment]
Hi @lforst 
the reason why clicking the escape spandetails sidepanel is not closing is that it's a route (`/traces/:traceId/:spanId`)and in the spotlight when escape is clicked, we navigate to the previous route in history.

the solution which we can implement here is to remove the spanId from the route(not treating the sidepanel as a page) and open the sidepanel based on the active span state.


Also, with this commit - https://github.com/getsentry/spotlight/commit/14eadb97f34d3430e201cc3a29170bf22f02e4ff
we added a UX of treating sidepanel as a dialogue box in which on clicking outside of panel close the sidepanel

**Comment by Shubhdeep12** [comment]
Hi,
closing this as the issue looks resolved.
