### ISSUE TITLE
Export Integration for use with custom integrations

### ISSUE THREAD

**Issue by MisterJimson** [getsentry/spotlight#354]
https://github.com/getsentry/spotlight/blob/0ff482719434864760d4308a36493963d4830159/packages/overlay/src/integrations/integration.ts#L11

`Integration` is used for the first party integrations. Would be nice to use this type for custom integrations as well.

**Comment by Shubhdeep12** [comment]
Yes @MisterJimson we are using this type for custom integrations as well.

**Comment by MisterJimson** [comment]
Yes thanks. It's not exported in the main index file so it's difficult to use when building custom integrations. Can it be re exported from `https://github.com/getsentry/spotlight/blob/main/packages/overlay/src/index.tsx`?

**Comment by BYK** [comment]
Apologies for the very late response @MisterJimson. I agree that it would be nice for these types to be easily available. I'm not a fan of re-exporting as I don't think we can get away by just exporting that type. We should export some more surrounding types. That said I couldn't find a way for `tsc` to pick up our already bundled `d.ts` files for these paths as we bundle the entire thing into a single `.js` module.

If anyone knows how to do this without reexporting (as we already have the relevant `d.ts` files with proper type exports in place), please do share how. Otherwise I'll go with the re-export path as @MisterJimson suggested.
