### ISSUE TITLE
@spotlightjs/overlay defines a `require` export with `umd` but the file is not generated

### ISSUE THREAD

**Issue by BYK** [getsentry/spotlight#625]
From https://github.com/getsentry/spotlight/issues/609#issuecomment-2539055113

Essentially, we defined a `require` field in `exports` inside `package.json`, pointing to a `spotlight.umd.js` file which doesn't exist since we don't build it.

**Comment by BYK** [comment]
@william-stacken - Do you think your build system take the `es` version and process that accordingly?

**Comment by william-stacken** [comment]
I am not a very experienced node developer, so I am not fully certain what you are asking. But changing the `require` field of package.json to `sentry-spotlight.js` does indeed work.

I think our build system does not support `import`, because removing the `require` field causes the error `Module not found: Error: Package path . is not exported from package /tmp/broccoli-22414IdHLV4Arbl5L/cache-369-webpack_bundler_ember_auto_import_webpack/node_modules/@spotlightjs/overlay (see exports field in /tmp/broccoli-22414IdHLV4Arbl5L/cache-369-webpack_bundler_ember_auto_import_webpack/node_modules/@spotlightjs/overlay/package.json)`.

**Comment by BYK** [comment]
@william-stacken thanks a lot for the feedback. I've found a good way to generate the UMD bundle which should be more compatible with all bundlers. Fix merged and hoping to cut a new release today.
